name: TestRail
run-name: Run ${{github.event.inputs.test_category || 'All'}} tests

on:
  workflow_dispatch:
    inputs:
      test_category:
       description: 'Select test category'
       type: choice
       options:
       - All
       - Smoke
       - Login
       - Project
       - Milestone
       - Cleaner
       - ToFail
 
  schedule:
    - cron: '40 13 * * *'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set up environment variables
      run: |
        echo "TESTRAIL_USERNAME=${{secrets.TESTRAIL_USERNAME}}" >> $GITHUB_ENV
        echo "TESTRAIL_PASSWORD=${{secrets.TESTRAIL_PASSWORD}}" >> $GITHUB_ENV
          
    # Execute all tests in the solution
    - name: Execute All tests
      if: ${{ github.event.inputs.test_category == 'All' || github.event_name == 'schedule' }}
      run: dotnet test --filter "Category!=ProjectCleaner&Category!=DatabaseTests&Category!=ToFail"

    # Execute smoke tests
    - name: Execute Smoke Tests
      if: github.event.inputs.test_category == 'Smoke'
      run: dotnet test --filter Category=SmokeTests

    # Execute login tests
    - name: Execute Login Tests
      if: github.event.inputs.test_category == 'Login'
      run: dotnet test --filter "Category=LoginTests&Category!=ToFail"

    # Execute project tests
    - name: Execute Project Tests
      if: github.event.inputs.test_category == 'Project'
      run: dotnet test --filter Category=ProjectTests

    # Execute milestone tests
    - name: Execute Milestone Tests
      if: github.event.inputs.test_category == 'Milestone'
      run: dotnet test --filter Category=MilestoneTests

    # Execute cleaner tests
    - name: Execute Cleaner Tests
      if: github.event.inputs.test_category == 'Cleaner'
      run: dotnet test --filter Category=ProjectCleaner

    # Execute tests to fail
    - name: Execute Cleaner Tests
      if: github.event.inputs.test_category == 'ToFail'
      run: dotnet test --filter Category=ToFail

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: ./bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
